spring:
  application:
    name: gonnag

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://svc.sel3.cloudtype.app:31993/swe_db
    driver-class-name: org.postgresql.Driver
    username: swe_admin
    password: 1111

jwt:
  secret-key: "TqL%K$zY8p!rAsD9fHjM3bXcvP!sFd@SgVkYp#wZ@tGqL%K$zY8p!rAsD9fH"
  expiration-ms: 3600000